### ISSUE TITLE
请问下你的docker容器是基于ubuntu的吗？为什么没有apt命令？

### ISSUE THREAD

**Issue by wsh3776** [noobcoderT/myvimrc#1]
你好，我看了这篇文章https://traceme.space/blog/page/6/zshoh-my-zshtmuxvimdocker/
用了下你的docker镜像，环境都配好了，但是怎么没有基础的安装命令？你是用什么安装软件的
![image](https://user-images.githubusercontent.com/46078304/95804646-e4eb8480-0d35-11eb-9b24-d584c47d2324.png)

**Comment by noobcoderT** [comment]
> 你好，我看了这篇文章https://traceme.space/blog/page/6/zshoh-my-zshtmuxvimdocker/
> 用了下你的docker镜像，环境都配好了，但是怎么没有基础的安装命令？你是用什么安装软件的
> ![image](https://user-images.githubusercontent.com/46078304/95804646-e4eb8480-0d35-11eb-9b24-d584c47d2324.png)

你好，这个docker镜像是基于alpine的，一个轻量级的linux操作系统，软件包管理器是apk。

**Comment by wsh3776** [comment]
> > 你好，我看了这篇文章https://traceme.space/blog/page/6/zshoh-my-zshtmuxvimdocker/
> > 用了下你的docker镜像，环境都配好了，但是怎么没有基础的安装命令？你是用什么安装软件的
> > ![image](https://user-images.githubusercontent.com/46078304/95804646-e4eb8480-0d35-11eb-9b24-d584c47d2324.png)
> 
> 你好，这个docker镜像是基于alpine的，一个轻量级的linux操作系统，软件包管理器是apk。

好的，谢谢！

**Comment by wsh3776** [comment]
> > 你好，我看了这篇文章https://traceme.space/blog/page/6/zshoh-my-zshtmuxvimdocker/
> > 用了下你的docker镜像，环境都配好了，但是怎么没有基础的安装命令？你是用什么安装软件的
> > ![image](https://user-images.githubusercontent.com/46078304/95804646-e4eb8480-0d35-11eb-9b24-d584c47d2324.png)
> 
> 你好，这个docker镜像是基于alpine的，一个轻量级的linux操作系统，软件包管理器是apk。

再问下这些红色的空格提示框以及这个红色的边界，要在哪里去掉？
![image](https://user-images.githubusercontent.com/46078304/96687622-bb280280-13b2-11eb-9f81-00f7f6e4048f.png)

**Comment by noobcoderT** [comment]
> > > 你好，我看了这篇文章https://traceme.space/blog/page/6/zshoh-my-zshtmuxvimdocker/
> > > 用了下你的docker镜像，环境都配好了，但是怎么没有基础的安装命令？你是用什么安装软件的
> > > ![image](https://user-images.githubusercontent.com/46078304/95804646-e4eb8480-0d35-11eb-9b24-d584c47d2324.png)
> > 
> > 
> > 你好，这个docker镜像是基于alpine的，一个轻量级的linux操作系统，软件包管理器是apk。
> 
> 再问下这些红色的空格提示框以及这个红色的边界，要在哪里去掉？
> ![image](https://user-images.githubusercontent.com/46078304/96687622-bb280280-13b2-11eb-9f81-00f7f6e4048f.png)

1、红色的空格提示框是通过my_plugins中vim-trailing-whitespace这个插件做的，除了提示空白字符之外，还可以实现,t快捷键快捷去除空白字符。如果要去掉直接删除my_plugins下的vim-trailing-whitespace目录即可。
2、红色边界是一个代码列宽的提示，要去掉的话注释掉my_configs.vim中的"set textwidth"这一行即可。

**Comment by wsh3776** [comment]
> > > > 你好，我看了这篇文章https://traceme.space/blog/page/6/zshoh-my-zshtmuxvimdocker/
> > > > 用了下你的docker镜像，环境都配好了，但是怎么没有基础的安装命令？你是用什么安装软件的
> > > > ![image](https://user-images.githubusercontent.com/46078304/95804646-e4eb8480-0d35-11eb-9b24-d584c47d2324.png)
> > > 
> > > 
> > > 你好，这个docker镜像是基于alpine的，一个轻量级的linux操作系统，软件包管理器是apk。
> > 
> > 
> > 再问下这些红色的空格提示框以及这个红色的边界，要在哪里去掉？
> > ![image](https://user-images.githubusercontent.com/46078304/96687622-bb280280-13b2-11eb-9f81-00f7f6e4048f.png)
> 
> 1、红色的空格提示框是通过my_plugins中vim-trailing-whitespace这个插件做的，除了提示空白字符之外，还可以实现,t快捷键快捷去除空白字符。如果要去掉直接删除my_plugins下的vim-trailing-whitespace目录即可。
> 2、红色边界是一个代码列宽的提示，要去掉的话注释掉my_configs.vim中的"set textwidth"这一行即可。

谢谢！
